name: redlink_flutter_sdk_example
description: Demonstrates how to use the redlink_flutter_sdk plugin.
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  redlink_flutter_sdk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
